# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'path/to/design.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.
import sys
from PyQt5 import QtWidgets, QtGui
from PyQt5 import uic
from PyQt5.QtWidgets import QMainWindow, QMessageBox, QStyleFactory


class Laba2(QMainWindow):
    def __init__(self):
        super(Laba2, self).__init__()
        uic.loadUi('laba2.ui', self)
        self.left_pos_key = QtGui.QPixmap("C:\\Users\\Roman\\Desktop\\лево.png")
        self.right_pos_key = QtGui.QPixmap("C:\\Users\\Roman\\Desktop\\право.png")
        self.key_slider.valueChanged.connect(self.change_picture_key)


    def change_picture_key(self):
        print(self.key_slider.value())
        if self.key_slider.value() == 0:
            self.label_key.setPixmap(self.left_pos_key)
        elif self.key_slider.value() == 2:
            self.label_key.setPixmap(self.right_pos_key)




if __name__ == '__main__':
    app = QtWidgets.QApplication(sys.argv)
    window = Laba2()
    window.show()
    app.exec_()
    input()
