# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'F:\Projects\SimulationOfLaboratoryWork\forms_ui\authorization.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_authorization_window(object):
    def setupUi(self, authorization_window):
        authorization_window.setObjectName("authorization_window")
        authorization_window.setWindowModality(QtCore.Qt.NonModal)
        authorization_window.resize(560, 433)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(authorization_window.sizePolicy().hasHeightForWidth())
        authorization_window.setSizePolicy(sizePolicy)
        authorization_window.setStyleSheet("background-color: rgb(176,193,208);")
        self.centralwidget = QtWidgets.QWidget(authorization_window)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(120, 70, 321, 101))
        font = QtGui.QFont()
        font.setFamily("Comic Sans MS")
        font.setPointSize(14)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(9)
        self.label.setFont(font)
        self.label.setStyleSheet("font: 75 14pt \"Comic Sans MS\";")
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setWordWrap(True)
        self.label.setObjectName("label")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(200, 300, 151, 31))
        self.pushButton.setObjectName("pushButton")
        self.lineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit.setGeometry(QtCore.QRect(30, 210, 491, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lineEdit.setFont(font)
        self.lineEdit.setEchoMode(QtWidgets.QLineEdit.Password)
        self.lineEdit.setObjectName("lineEdit")
        authorization_window.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(authorization_window)
        self.statusbar.setObjectName("statusbar")
        authorization_window.setStatusBar(self.statusbar)
        self.menubar = QtWidgets.QMenuBar(authorization_window)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 560, 21))
        self.menubar.setObjectName("menubar")
        authorization_window.setMenuBar(self.menubar)

        self.retranslateUi(authorization_window)
        QtCore.QMetaObject.connectSlotsByName(authorization_window)

    def retranslateUi(self, authorization_window):
        _translate = QtCore.QCoreApplication.translate
        authorization_window.setWindowTitle(_translate("authorization_window", "Авторизация"))
        self.label.setText(_translate("authorization_window", "Введите пароль."))
        self.pushButton.setText(_translate("authorization_window", "Авторизация"))
