# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'F:\Projects\Simulation_Of_Laboratory_Works\forms_ui\info_laba.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_info_laba(object):
    def setupUi(self, info_laba):
        info_laba.setObjectName("info_laba")
        info_laba.resize(602, 742)
        info_laba.setMinimumSize(QtCore.QSize(602, 742))
        info_laba.setMaximumSize(QtCore.QSize(602, 742))
        self.verticalLayout = QtWidgets.QVBoxLayout(info_laba)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.scrollArea = QtWidgets.QScrollArea(info_laba)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 600, 740))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.scrollAreaWidgetContents.sizePolicy().hasHeightForWidth())
        self.scrollAreaWidgetContents.setSizePolicy(sizePolicy)
        self.scrollAreaWidgetContents.setMinimumSize(QtCore.QSize(600, 0))
        self.scrollAreaWidgetContents.setMaximumSize(QtCore.QSize(600, 16777215))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.scrollAreaWidgetContents)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.verticalLayout.addWidget(self.scrollArea)

        self.retranslateUi(info_laba)
        QtCore.QMetaObject.connectSlotsByName(info_laba)

    def retranslateUi(self, info_laba):
        _translate = QtCore.QCoreApplication.translate
        info_laba.setWindowTitle(_translate("info_laba", "Инструкция по выполненю"))
